variables:
  DOCKER_REGISTRY: 073068687739.dkr.ecr.ap-southeast-2.amazonaws.com
  AWS_DEFAULT_REGION: ap-southeast-2
  APP_NAME: live.pineapple.net.au
  HELM_NAME: live-pineapple-net-au
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  - test
  - build
  - prod

.publish:
  variables:
    CI_PRE_CLONE_SCRIPT: umask 022
  stage: build
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - amazon-linux-extras install docker
    - aws --version
    - docker --version

publish:
  extends: .publish
  environment:
    name: build php
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA .
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$APP_NAME:$CI_COMMIT_SHA

.deploy-prod:
  stage: prod
  image:
    name: public.ecr.aws/e9l9n7j8/helm-aws-cli:latest
    entrypoint: [""]
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    - aws --region ap-southeast-2  eks update-kubeconfig --name dgtek-prod-infra-cluster
  rules:
    - if: $CI_COMMIT_TAG
      when: manual

deploy-prod:
  extends: .deploy-prod
  script:
    - cd .helm
    - >
      helm upgrade $HELM_NAME
      --namespace $HELM_NAME --install .
      --set image.tag=$CI_COMMIT_SHA
    - cd ../../
  environment:
    name: prod dgtek net

lint:
  stage: test
  image: node:12-alpine
  before_script:
    - yarn install
  script:
    - yarn lint
