apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.image.name }}
  annotations:
    kubernetes.io/ingress.class: nginx-public
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
    alb.ingress.kubernetes.io/scheme: internet-facing
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.uploadSize }}
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      add_header X-Frame-Options "SAMEORIGIN";
      add_header X-Content-Type-Options nosniff;
      add_header X-XSS-Protection 1;
      add_header X-Permitted-Cross-Domain-Policies none;
      proxy_hide_header X-Powered-By;
      server_tokens off;
    nginx.ingress.kubernetes.io/limit-rpm: "{{ .Values.ingress.rateLimit }}"
spec:
  rules:
    - host: "{{ .Values.domain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.image.name }}
              servicePort: http
    - host: "www.{{ .Values.domain }}"
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.image.name }}
              servicePort: http
  tls:
    - hosts:
      - "{{ .Values.domain }}"
      - "www.{{ .Values.domain }}"
      secretName: "{{ .Values.slug}}-tls"
